chore: setup import action ( fix #13 )

diff --git a/.github/workflows/import.yaml b/.github/workflows/import.yaml
--- a/.github/workflows/import.yaml
+++ b/.github/workflows/import.yaml
@@ -2,19 +2,71 @@ name: import
 
 on:
   workflow_dispatch:
-  push:
-    branches:
-      - main
+    inputs:
+      debug:
+        description: "debug mode"
+        required: false
+        default: false
+        type: boolean
+  schedule:
+    - cron: "0 */3 * * *"
 
 jobs:
   import:
     runs-on: ubuntu-latest
+    timeout-minutes: 3
     steps:
-      - uses: actions/checkout@v3
+      - name: Generate token
+        uses: tibdex/github-app-token@v1
+        with:
+          app_id: ${{ secrets.MY_APP_ID }}
+          private_key: ${{ secrets.MY_APP_PRIVATE_KEY }}
+        id: my_app
+
+      - name: Checkout source
+        uses: actions/checkout@v3
+        with:
+          token: ${{ steps.my_app.outputs.token }}
+
       - uses: ega4432/notion-to-markdown-action@v0
         with:
-          output_path: ./src/pages/notes
+          output_path: ./src/content/blog
+          filename_property: slug
         env:
           NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
           NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
-      - run: ls -ltra output
+
+      - name: Configure git
+        run: |
+          git config --local user.email "actions@github.com"
+          git config --local user.name "GitHub Actions"
+
+      - name: Output diff
+        if: ${{ github.event_name == 'workflow_dispatch' }}
+        run: |
+          git status --short
+          git diff --name-only
+
+      - name: Delete `slug` property from front matter
+        run: |
+          git diff --name-only ./src/content/blog/ | xargs sed -i '/^slug:/d'
+
+      - name: Move images to `public` directory
+        run: |
+          ls -d ./src/content/blog/*/ | grep -Ev "book-review" | xargs -I {} mv -fv {} ./public/images/blog/
+
+      # - name: Check diff
+      #   id: diff
+      #   run: |
+      #     if [ "$(git diff --name-only ./src/content/blog | wc -l)" -gt "0" ]; then
+      #       git diff --name-only ./src/content/blog
+      #       exit 1
+      #     fi
+      #   continue-on-error: true
+
+      # - name: Commit only published contents & push
+      #   if: ${{ steps.diff.outcome == 'failure' }}
+      #   run: |
+      #     git diff --name-only ./src/content/blog | xargs grep -L "draft: true" | xargs git add
+      #     git commit -m '[bot] Automatically import contents from Notion'
+      #     git push
